### ISSUE TITLE
[Bug]: [ERROR]Fail to bind embedding model: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

### ISSUE THREAD

**Issue by liuxc1** [infiniflow/ragflow#6170]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### RAGFlow workspace code commit ID

0.17.0

### RAGFlow image version

0.17.0

### Other environment information

```Markdown

```

### Actual behavior

使用docker部署时，启用多个解析线程。宿主机为多网卡时产生如下异常。
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/

PY=python3
if [[ -z "$WS" || $WS -lt 1 ]]; then
  WS=5
fi

[ERROR]Fail to bind embedding model: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

### Steps to reproduce

```Markdown
使用docker部署时，启用多个解析线程。宿主机为多网卡时产生如下异常。
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/

PY=python3
if [[ -z "$WS" || $WS -lt 1 ]]; then
  WS=5
fi

[ERROR]Fail to bind embedding model: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)
```

**Comment by Yannnnnnny** [comment]
Since the issue has been resolved, I'll close this issue for now. Feel free to open a new issue if you run into any further problems.
