### ISSUE TITLE
[Question]: parse document

### ISSUE THREAD

**Issue by zhanghengjiayou** [infiniflow/ragflow#7214]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Describe your problem

08:58:15 Task has been received.
08:58:18 Page(1~100000001): Start to parse.
08:58:18 Page(1~100000001): Finish parsing.
08:58:18 Page(1~100000001): Start to generate keywords for every chunk ...
09:00:41 Page(1~100000001): Keywords generation 2 chunks completed in 143.36s
09:00:41 Page(1~100000001): Generate 2 chunks
09:00:42 Page(1~100000001): [ERROR]Generate embedding error:NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)
09:00:42 [ERROR][Exception]: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

**Comment by zhanghengjiayou** [comment]
谢谢，已解决

**Comment by zhanghengjiayou** [comment]
> I found some similar threads related to the NCCL Error 2 issue:
> 
> 1. An open issue suggests that the communication between GPUs fails, and you can restrict the model to run on one GPU to solve this issue [[1]](https://github.com/infiniflow/ragflow/issues/3432).
> 2. A closed issue recommends specifying the use of only one GPU with Docker by adding the following configuration:
>    devices:
>      - driver: nvidia
>        count: 1
>        capabilities: [gpu]
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    [[2]](https://github.com/infiniflow/ragflow/issues/1643).
> 
> Additionally, to resolve the NCCL Error 2 during the embedding generation process, you can adjust the Docker container's shared memory size (`shm_size`) to a larger value, such as 12GB, depending on your GPU memory size [[3]](https://github.com/infiniflow/ragflow/issues/5954).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu)._
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/d701f51f-05b6-4ce6-8982-d981afb866c6?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/d701f51f-05b6-4ce6-8982-d981afb866c6?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/d701f51f-05b6-4ce6-8982-d981afb866c6?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/d701f51f-05b6-4ce6-8982-d981afb866c6?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/d701f51f-05b6-4ce6-8982-d981afb866c6?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/d701f51f-05b6-4ce6-8982-d981afb866c6?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/d701f51f-05b6-4ce6-8982-d981afb866c6?feedback_type=other)

谢谢，已解决
